import type { Metadata } from "next";
import "./globals.css";
import { geistSans, geistMono } from "@/fonts/font";
import Navbar from "@/components/custom/navbar";
import RootFooter from "@/components/custom/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-black from-30% via-blue-950 via-70% to-blue-800 h-screen w-screen text-white flex`}
			>
				<main>
					<Navbar />
					{children}
				</main>
				<RootFooter />
			</body>
		</html>
	);
}
